#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'

require 'gli'

require "ratoap"

include GLI::App

version Ratoap::VERSION

program_desc 'Run any test on any platforms'

desc 'Init config files'
command :init do |c|
  c.flag [:d, :driver], desc: 'set driver', type: String, default_value: 'vagrant'

  c.action do |global_options, options, args|
    # Ratoap::CLI::INIT.run(global_options, options, args)
    puts global_options.inspect
    puts options.inspect
    puts args.inspect
  end
end

exit run(ARGV)

